### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function get_periods() on bool

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay-memberpress#8]
From a user:

```
[12-Aug-2021 18:38:54 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_periods() on bool in wp-content/plugins/pronamic-ideal/vendor/wp-pay-extensions/memberpress/src/Extension.php:453
Stack trace:
#0 wp-includes/class-wp-hook.php(303): Pronamic\WordPress\Pay\Extensions\MemberPress\Extension->transaction_email_params()
#1 wp-includes/plugin.php(189): WP_Hook->apply_filters()
#2 wp-content/plugins/memberpress/app/lib/MeprHooks.php(33): apply_filters()
#3 wp-content/plugins/memberpress/app/lib/MeprHooks.php(15): MeprHooks::call()
#4 wp-content/plugins/memberpress/app/helpers/MeprTransactionsHelper.php(233): MeprHooks::apply_filters()
#5 wp-content/plugins/memberpress/app/lib/MeprUtils.php(1547): MeprTransactionsHelper::get_email_params()
#6 in wp-content/plugins/pronamic-ideal/vendor/wp-pay-extensions/memberpress/src/Extension.php on line 453
```

_Internal HelpScout ticket: https://secure.helpscout.net/conversation/2123834698/25048?folderId=1425710_

https://plugins.trac.wordpress.org/browser/pronamic-ideal/tags/9.2.1/vendor/wp-pay-extensions/memberpress/src/Extension.php#L453

**Comment by remcotolsma** [comment]
Never mind, this was an error from `12-Aug-2021` 😏.
